// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\FFTHDLOptimizedExample_Burst\Complex4Multiply.v
// Created: 2024-05-11 18:31:33
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Complex4Multiply
// Source Path: FFTHDLOptimizedExample_Burst/FFT Burst/FFT/MINRESRX2_BUTTERFLY/Complex4Multiply
// Hierarchy Level: 3
// Model version: 8.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Complex4Multiply
          (clk,
           reset,
           btfIn2_re,
           btfIn2_im,
           din2Dly_vld,
           twdl_re,
           twdl_im,
           dinXTwdl_re,
           dinXTwdl_im,
           dinXTwdl_vld);


  input   clk;
  input   reset;
  input   signed [24:0] btfIn2_re;  // sfix25_En13
  input   signed [24:0] btfIn2_im;  // sfix25_En13
  input   din2Dly_vld;
  input   signed [24:0] twdl_re;  // sfix25_En23
  input   signed [24:0] twdl_im;  // sfix25_En23
  output  signed [50:0] dinXTwdl_re;  // sfix51_En36
  output  signed [50:0] dinXTwdl_im;  // sfix51_En36
  output  dinXTwdl_vld;


  reg signed [24:0] din_re_reg;  // sfix25_En13
  reg signed [24:0] din_im_reg;  // sfix25_En13
  reg signed [24:0] twdl_re_reg;  // sfix25_En23
  reg signed [24:0] twdl_im_reg;  // sfix25_En23
  reg signed [24:0] Complex4Multiply_din1_re_pipe1;  // sfix25
  reg signed [24:0] Complex4Multiply_din1_im_pipe1;  // sfix25
  reg signed [49:0] Complex4Multiply_mult1_re_pipe1;  // sfix50
  reg signed [49:0] Complex4Multiply_mult2_re_pipe1;  // sfix50
  reg signed [49:0] Complex4Multiply_mult1_im_pipe1;  // sfix50
  reg signed [49:0] Complex4Multiply_mult2_im_pipe1;  // sfix50
  reg signed [24:0] Complex4Multiply_twiddle_re_pipe1;  // sfix25
  reg signed [24:0] Complex4Multiply_twiddle_im_pipe1;  // sfix25
  reg signed [49:0] prod1_re;  // sfix50_En36
  reg signed [49:0] prod1_im;  // sfix50_En36
  reg signed [49:0] prod2_re;  // sfix50_En36
  reg signed [49:0] prod2_im;  // sfix50_En36
  reg  din_vld_dly1;
  reg  din_vld_dly2;
  reg  din_vld_dly3;
  reg  prod_vld;
  reg signed [50:0] Complex4Add_multRes_re_reg;  // sfix51
  reg signed [50:0] Complex4Add_multRes_im_reg;  // sfix51
  reg  Complex4Add_prod_vld_reg1;
  reg signed [49:0] Complex4Add_prod1_re_reg;  // sfix50
  reg signed [49:0] Complex4Add_prod1_im_reg;  // sfix50
  reg signed [49:0] Complex4Add_prod2_re_reg;  // sfix50
  reg signed [49:0] Complex4Add_prod2_im_reg;  // sfix50
  wire signed [50:0] Complex4Add_multRes_re_reg_next;  // sfix51_En36
  wire signed [50:0] Complex4Add_multRes_im_reg_next;  // sfix51_En36
  wire signed [50:0] Complex4Add_sub_cast;  // sfix51_En36
  wire signed [50:0] Complex4Add_sub_cast_1;  // sfix51_En36
  wire signed [50:0] Complex4Add_add_cast;  // sfix51_En36
  wire signed [50:0] Complex4Add_add_cast_1;  // sfix51_En36
  wire signed [50:0] mulResFP_re;  // sfix51_En36
  wire signed [50:0] mulResFP_im;  // sfix51_En36
  reg  dinXTwdl_vld_1;


  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        din_re_reg <= 25'sb0000000000000000000000000;
      end
      else begin
        din_re_reg <= btfIn2_re;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        din_im_reg <= 25'sb0000000000000000000000000;
      end
      else begin
        din_im_reg <= btfIn2_im;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        twdl_re_reg <= 25'sb0000000000000000000000000;
      end
      else begin
        twdl_re_reg <= twdl_re;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        twdl_im_reg <= 25'sb0000000000000000000000000;
      end
      else begin
        twdl_im_reg <= twdl_im;
      end
    end



  // Complex4Multiply
  always @(posedge clk)
    begin : Complex4Multiply_1_process
      prod1_re <= Complex4Multiply_mult1_re_pipe1;
      prod2_re <= Complex4Multiply_mult2_re_pipe1;
      prod1_im <= Complex4Multiply_mult1_im_pipe1;
      prod2_im <= Complex4Multiply_mult2_im_pipe1;
      Complex4Multiply_mult1_re_pipe1 <= Complex4Multiply_din1_re_pipe1 * Complex4Multiply_twiddle_re_pipe1;
      Complex4Multiply_mult2_re_pipe1 <= Complex4Multiply_din1_im_pipe1 * Complex4Multiply_twiddle_im_pipe1;
      Complex4Multiply_mult1_im_pipe1 <= Complex4Multiply_din1_re_pipe1 * Complex4Multiply_twiddle_im_pipe1;
      Complex4Multiply_mult2_im_pipe1 <= Complex4Multiply_din1_im_pipe1 * Complex4Multiply_twiddle_re_pipe1;
      Complex4Multiply_twiddle_re_pipe1 <= twdl_re_reg;
      Complex4Multiply_twiddle_im_pipe1 <= twdl_im_reg;
      Complex4Multiply_din1_re_pipe1 <= din_re_reg;
      Complex4Multiply_din1_im_pipe1 <= din_im_reg;
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        din_vld_dly1 <= 1'b0;
      end
      else begin
        din_vld_dly1 <= din2Dly_vld;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        din_vld_dly2 <= 1'b0;
      end
      else begin
        din_vld_dly2 <= din_vld_dly1;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        din_vld_dly3 <= 1'b0;
      end
      else begin
        din_vld_dly3 <= din_vld_dly2;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        prod_vld <= 1'b0;
      end
      else begin
        prod_vld <= din_vld_dly3;
      end
    end



  // Complex4Add
  always @(posedge clk or posedge reset)
    begin : Complex4Add_process
      if (reset == 1'b1) begin
        Complex4Add_multRes_re_reg <= 51'sh0000000000000;
        Complex4Add_multRes_im_reg <= 51'sh0000000000000;
        Complex4Add_prod1_re_reg <= 50'sh0000000000000;
        Complex4Add_prod1_im_reg <= 50'sh0000000000000;
        Complex4Add_prod2_re_reg <= 50'sh0000000000000;
        Complex4Add_prod2_im_reg <= 50'sh0000000000000;
        Complex4Add_prod_vld_reg1 <= 1'b0;
        dinXTwdl_vld_1 <= 1'b0;
      end
      else begin
        Complex4Add_multRes_re_reg <= Complex4Add_multRes_re_reg_next;
        Complex4Add_multRes_im_reg <= Complex4Add_multRes_im_reg_next;
        Complex4Add_prod1_re_reg <= prod1_re;
        Complex4Add_prod1_im_reg <= prod1_im;
        Complex4Add_prod2_re_reg <= prod2_re;
        Complex4Add_prod2_im_reg <= prod2_im;
        dinXTwdl_vld_1 <= Complex4Add_prod_vld_reg1;
        Complex4Add_prod_vld_reg1 <= prod_vld;
      end
    end

  assign Complex4Add_sub_cast = {Complex4Add_prod1_re_reg[49], Complex4Add_prod1_re_reg};
  assign Complex4Add_sub_cast_1 = {Complex4Add_prod2_re_reg[49], Complex4Add_prod2_re_reg};
  assign Complex4Add_multRes_re_reg_next = Complex4Add_sub_cast - Complex4Add_sub_cast_1;
  assign Complex4Add_add_cast = {Complex4Add_prod1_im_reg[49], Complex4Add_prod1_im_reg};
  assign Complex4Add_add_cast_1 = {Complex4Add_prod2_im_reg[49], Complex4Add_prod2_im_reg};
  assign Complex4Add_multRes_im_reg_next = Complex4Add_add_cast + Complex4Add_add_cast_1;
  assign mulResFP_re = Complex4Add_multRes_re_reg;
  assign mulResFP_im = Complex4Add_multRes_im_reg;



  assign dinXTwdl_re = mulResFP_re;

  assign dinXTwdl_im = mulResFP_im;

  assign dinXTwdl_vld = dinXTwdl_vld_1;

endmodule  // Complex4Multiply

