// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\FFTHDLOptimizedExample_Burst\FFT_Burst.v
// Created: 2024-05-11 18:31:33
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FFT_Burst
// Source Path: FFTHDLOptimizedExample_Burst/FFT Burst
// Hierarchy Level: 0
// Model version: 8.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FFT_Burst
          (clk,
           reset,
           DataIn_re,
           DataIn_im,
           ValidIn,
           DataOut_re,
           DataOut_im,
           ValidOut,
           Ready);


  input   clk;
  input   reset;
  input   signed [15:0] DataIn_re;  // sfix16_En13
  input   signed [15:0] DataIn_im;  // sfix16_En13
  input   ValidIn;
  output  signed [24:0] DataOut_re;  // sfix25_En13
  output  signed [24:0] DataOut_im;  // sfix25_En13
  output  ValidOut;
  output  Ready;


  wire signed [24:0] FFT_out1_re;  // sfix25_En13
  wire signed [24:0] FFT_out1_im;  // sfix25_En13
  wire FFT_out2;
  wire FFT_out3;


  FFT u_FFT (.clk(clk),
             .reset(reset),
             .dataIn_re(DataIn_re),  // sfix16_En13
             .dataIn_im(DataIn_im),  // sfix16_En13
             .validIn(ValidIn),
             .dataOut_re(FFT_out1_re),  // sfix25_En13
             .dataOut_im(FFT_out1_im),  // sfix25_En13
             .validOut(FFT_out2),
             .ready(FFT_out3)
             );
  assign DataOut_re = FFT_out1_re;

  assign DataOut_im = FFT_out1_im;

  assign ValidOut = FFT_out2;

  assign Ready = FFT_out3;

endmodule  // FFT_Burst

