// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\FFTHDLOptimizedExample_Burst\MINRESRX2FFT_BTFSEL.v
// Created: 2024-05-11 18:31:33
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MINRESRX2FFT_BTFSEL
// Source Path: FFTHDLOptimizedExample_Burst/FFT Burst/FFT/MINRESRX2FFT_BTFSEL
// Hierarchy Level: 2
// Model version: 8.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MINRESRX2FFT_BTFSEL
          (clk,
           reset,
           din_1_re,
           din_1_im,
           validIn,
           rdy,
           dMemOut1_re,
           dMemOut1_im,
           dMemOut2_re,
           dMemOut2_im,
           dMemOut_vld,
           stage,
           initIC,
           btfIn1_re,
           btfIn1_im,
           btfIn2_re,
           btfIn2_im,
           btfIn_vld);


  input   clk;
  input   reset;
  input   signed [24:0] din_1_re;  // sfix25_En13
  input   signed [24:0] din_1_im;  // sfix25_En13
  input   validIn;
  input   rdy;
  input   signed [24:0] dMemOut1_re;  // sfix25_En13
  input   signed [24:0] dMemOut1_im;  // sfix25_En13
  input   signed [24:0] dMemOut2_re;  // sfix25_En13
  input   signed [24:0] dMemOut2_im;  // sfix25_En13
  input   dMemOut_vld;
  input   [3:0] stage;  // ufix4
  input   initIC;
  output  signed [24:0] btfIn1_re;  // sfix25_En13
  output  signed [24:0] btfIn1_im;  // sfix25_En13
  output  signed [24:0] btfIn2_re;  // sfix25_En13
  output  signed [24:0] btfIn2_im;  // sfix25_En13
  output  btfIn_vld;


  reg signed [24:0] minResRX2FFTBTFSEL_btfIn1Reg_re;  // sfix25
  reg signed [24:0] minResRX2FFTBTFSEL_btfIn1Reg_im;  // sfix25
  reg signed [24:0] minResRX2FFTBTFSEL_btfIn2Reg_re;  // sfix25
  reg signed [24:0] minResRX2FFTBTFSEL_btfIn2Reg_im;  // sfix25
  reg  minResRX2FFTBTFSEL_btfInReg_vld;
  reg [7:0] minResRX2FFTBTFSEL_cnt;  // ufix8
  reg [7:0] minResRX2FFTBTFSEL_cntMax;  // ufix8
  reg  minResRX2FFTBTFSEL_muxSel;
  reg signed [24:0] minResRX2FFTBTFSEL_dinReg1_re;  // sfix25
  reg signed [24:0] minResRX2FFTBTFSEL_dinReg1_im;  // sfix25
  reg signed [24:0] minResRX2FFTBTFSEL_dinReg2_re;  // sfix25
  reg signed [24:0] minResRX2FFTBTFSEL_dinReg2_im;  // sfix25
  reg signed [24:0] minResRX2FFTBTFSEL_dinReg3_re;  // sfix25
  reg signed [24:0] minResRX2FFTBTFSEL_dinReg3_im;  // sfix25
  reg signed [24:0] minResRX2FFTBTFSEL_dMemOut1Reg_re;  // sfix25
  reg signed [24:0] minResRX2FFTBTFSEL_dMemOut1Reg_im;  // sfix25
  reg signed [24:0] minResRX2FFTBTFSEL_dMemOut2Reg_re;  // sfix25
  reg signed [24:0] minResRX2FFTBTFSEL_dMemOut2Reg_im;  // sfix25
  reg  minResRX2FFTBTFSEL_dMemOutReg_vld;
  reg signed [24:0] minResRX2FFTBTFSEL_btfIn1Reg_re_next;  // sfix25_En13
  reg signed [24:0] minResRX2FFTBTFSEL_btfIn1Reg_im_next;  // sfix25_En13
  reg signed [24:0] minResRX2FFTBTFSEL_btfIn2Reg_re_next;  // sfix25_En13
  reg signed [24:0] minResRX2FFTBTFSEL_btfIn2Reg_im_next;  // sfix25_En13
  reg  minResRX2FFTBTFSEL_btfInReg_vld_next;
  reg [7:0] minResRX2FFTBTFSEL_cnt_next;  // ufix8
  reg [7:0] minResRX2FFTBTFSEL_cntMax_next;  // ufix8
  reg  minResRX2FFTBTFSEL_muxSel_next;
  reg signed [24:0] minResRX2FFTBTFSEL_dinReg1_re_next;  // sfix25_En13
  reg signed [24:0] minResRX2FFTBTFSEL_dinReg1_im_next;  // sfix25_En13
  reg signed [24:0] minResRX2FFTBTFSEL_dinReg2_re_next;  // sfix25_En13
  reg signed [24:0] minResRX2FFTBTFSEL_dinReg2_im_next;  // sfix25_En13
  reg signed [24:0] minResRX2FFTBTFSEL_dinReg3_re_next;  // sfix25_En13
  reg signed [24:0] minResRX2FFTBTFSEL_dinReg3_im_next;  // sfix25_En13
  reg signed [24:0] minResRX2FFTBTFSEL_dMemOut1Reg_re_next;  // sfix25_En13
  reg signed [24:0] minResRX2FFTBTFSEL_dMemOut1Reg_im_next;  // sfix25_En13
  reg signed [24:0] minResRX2FFTBTFSEL_dMemOut2Reg_re_next;  // sfix25_En13
  reg signed [24:0] minResRX2FFTBTFSEL_dMemOut2Reg_im_next;  // sfix25_En13
  reg  minResRX2FFTBTFSEL_dMemOutReg_vld_next;
  reg signed [24:0] btfIn1_re_1;  // sfix25_En13
  reg signed [24:0] btfIn1_im_1;  // sfix25_En13
  reg signed [24:0] btfIn2_re_1;  // sfix25_En13
  reg signed [24:0] btfIn2_im_1;  // sfix25_En13
  reg  btfIn_vld_1;


  // minResRX2FFTBTFSEL
  always @(posedge clk or posedge reset)
    begin : minResRX2FFTBTFSEL_process
      if (reset == 1'b1) begin
        minResRX2FFTBTFSEL_btfIn1Reg_re <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_btfIn1Reg_im <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_btfIn2Reg_re <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_btfIn2Reg_im <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_dinReg1_re <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_dinReg1_im <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_dinReg2_re <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_dinReg2_im <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_dinReg3_re <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_dinReg3_im <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_dMemOut1Reg_re <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_dMemOut1Reg_im <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_dMemOut2Reg_re <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_dMemOut2Reg_im <= 25'sb0000000000000000000000000;
        minResRX2FFTBTFSEL_cnt <= 8'b00000000;
        minResRX2FFTBTFSEL_cntMax <= 8'b00000000;
        minResRX2FFTBTFSEL_muxSel <= 1'b0;
        minResRX2FFTBTFSEL_btfInReg_vld <= 1'b0;
        minResRX2FFTBTFSEL_dMemOutReg_vld <= 1'b0;
      end
      else begin
        minResRX2FFTBTFSEL_btfIn1Reg_re <= minResRX2FFTBTFSEL_btfIn1Reg_re_next;
        minResRX2FFTBTFSEL_btfIn1Reg_im <= minResRX2FFTBTFSEL_btfIn1Reg_im_next;
        minResRX2FFTBTFSEL_btfIn2Reg_re <= minResRX2FFTBTFSEL_btfIn2Reg_re_next;
        minResRX2FFTBTFSEL_btfIn2Reg_im <= minResRX2FFTBTFSEL_btfIn2Reg_im_next;
        minResRX2FFTBTFSEL_btfInReg_vld <= minResRX2FFTBTFSEL_btfInReg_vld_next;
        minResRX2FFTBTFSEL_cnt <= minResRX2FFTBTFSEL_cnt_next;
        minResRX2FFTBTFSEL_cntMax <= minResRX2FFTBTFSEL_cntMax_next;
        minResRX2FFTBTFSEL_muxSel <= minResRX2FFTBTFSEL_muxSel_next;
        minResRX2FFTBTFSEL_dinReg1_re <= minResRX2FFTBTFSEL_dinReg1_re_next;
        minResRX2FFTBTFSEL_dinReg1_im <= minResRX2FFTBTFSEL_dinReg1_im_next;
        minResRX2FFTBTFSEL_dinReg2_re <= minResRX2FFTBTFSEL_dinReg2_re_next;
        minResRX2FFTBTFSEL_dinReg2_im <= minResRX2FFTBTFSEL_dinReg2_im_next;
        minResRX2FFTBTFSEL_dinReg3_re <= minResRX2FFTBTFSEL_dinReg3_re_next;
        minResRX2FFTBTFSEL_dinReg3_im <= minResRX2FFTBTFSEL_dinReg3_im_next;
        minResRX2FFTBTFSEL_dMemOut1Reg_re <= minResRX2FFTBTFSEL_dMemOut1Reg_re_next;
        minResRX2FFTBTFSEL_dMemOut1Reg_im <= minResRX2FFTBTFSEL_dMemOut1Reg_im_next;
        minResRX2FFTBTFSEL_dMemOut2Reg_re <= minResRX2FFTBTFSEL_dMemOut2Reg_re_next;
        minResRX2FFTBTFSEL_dMemOut2Reg_im <= minResRX2FFTBTFSEL_dMemOut2Reg_im_next;
        minResRX2FFTBTFSEL_dMemOutReg_vld <= minResRX2FFTBTFSEL_dMemOutReg_vld_next;
      end
    end

  always @(dMemOut1_im, dMemOut1_re, dMemOut2_im, dMemOut2_re, dMemOut_vld, din_1_im,
       din_1_re, initIC, minResRX2FFTBTFSEL_btfIn1Reg_im,
       minResRX2FFTBTFSEL_btfIn1Reg_re, minResRX2FFTBTFSEL_btfIn2Reg_im,
       minResRX2FFTBTFSEL_btfIn2Reg_re, minResRX2FFTBTFSEL_btfInReg_vld,
       minResRX2FFTBTFSEL_cnt, minResRX2FFTBTFSEL_cntMax,
       minResRX2FFTBTFSEL_dMemOut1Reg_im, minResRX2FFTBTFSEL_dMemOut1Reg_re,
       minResRX2FFTBTFSEL_dMemOut2Reg_im, minResRX2FFTBTFSEL_dMemOut2Reg_re,
       minResRX2FFTBTFSEL_dMemOutReg_vld, minResRX2FFTBTFSEL_dinReg1_im,
       minResRX2FFTBTFSEL_dinReg1_re, minResRX2FFTBTFSEL_dinReg2_im,
       minResRX2FFTBTFSEL_dinReg2_re, minResRX2FFTBTFSEL_dinReg3_im,
       minResRX2FFTBTFSEL_dinReg3_re, minResRX2FFTBTFSEL_muxSel, stage) begin
    minResRX2FFTBTFSEL_cnt_next = minResRX2FFTBTFSEL_cnt;
    minResRX2FFTBTFSEL_cntMax_next = minResRX2FFTBTFSEL_cntMax;
    minResRX2FFTBTFSEL_muxSel_next = minResRX2FFTBTFSEL_muxSel;
    case ( stage)
      4'b0000 :
        begin
          minResRX2FFTBTFSEL_btfIn1Reg_re_next = minResRX2FFTBTFSEL_dMemOut1Reg_re;
          minResRX2FFTBTFSEL_btfIn1Reg_im_next = minResRX2FFTBTFSEL_dMemOut1Reg_im;
          minResRX2FFTBTFSEL_btfIn2Reg_re_next = minResRX2FFTBTFSEL_dinReg3_re;
          minResRX2FFTBTFSEL_btfIn2Reg_im_next = minResRX2FFTBTFSEL_dinReg3_im;
        end
      default :
        begin
          if (minResRX2FFTBTFSEL_muxSel) begin
            minResRX2FFTBTFSEL_btfIn1Reg_re_next = minResRX2FFTBTFSEL_dMemOut2Reg_re;
            minResRX2FFTBTFSEL_btfIn1Reg_im_next = minResRX2FFTBTFSEL_dMemOut2Reg_im;
            minResRX2FFTBTFSEL_btfIn2Reg_re_next = minResRX2FFTBTFSEL_dMemOut1Reg_re;
            minResRX2FFTBTFSEL_btfIn2Reg_im_next = minResRX2FFTBTFSEL_dMemOut1Reg_im;
          end
          else begin
            minResRX2FFTBTFSEL_btfIn1Reg_re_next = minResRX2FFTBTFSEL_dMemOut1Reg_re;
            minResRX2FFTBTFSEL_btfIn1Reg_im_next = minResRX2FFTBTFSEL_dMemOut1Reg_im;
            minResRX2FFTBTFSEL_btfIn2Reg_re_next = minResRX2FFTBTFSEL_dMemOut2Reg_re;
            minResRX2FFTBTFSEL_btfIn2Reg_im_next = minResRX2FFTBTFSEL_dMemOut2Reg_im;
          end
        end
    endcase
    minResRX2FFTBTFSEL_dinReg3_re_next = minResRX2FFTBTFSEL_dinReg2_re;
    minResRX2FFTBTFSEL_dinReg2_re_next = minResRX2FFTBTFSEL_dinReg1_re;
    minResRX2FFTBTFSEL_dinReg1_re_next = din_1_re;
    minResRX2FFTBTFSEL_dinReg3_im_next = minResRX2FFTBTFSEL_dinReg2_im;
    minResRX2FFTBTFSEL_dinReg2_im_next = minResRX2FFTBTFSEL_dinReg1_im;
    minResRX2FFTBTFSEL_dinReg1_im_next = din_1_im;
    if (initIC) begin
      minResRX2FFTBTFSEL_cnt_next = 8'b00000000;
      minResRX2FFTBTFSEL_muxSel_next = 1'b0;
      case ( stage)
        4'b0000 :
          begin
            minResRX2FFTBTFSEL_cntMax_next = 8'b11111111;
          end
        default :
          begin
            minResRX2FFTBTFSEL_cntMax_next = minResRX2FFTBTFSEL_cntMax >> 8'd1;
          end
      endcase
    end
    else if (minResRX2FFTBTFSEL_dMemOutReg_vld) begin
      if (minResRX2FFTBTFSEL_cnt == minResRX2FFTBTFSEL_cntMax) begin
        minResRX2FFTBTFSEL_cnt_next = 8'b00000000;
        minResRX2FFTBTFSEL_muxSel_next =  ! minResRX2FFTBTFSEL_muxSel;
      end
      else begin
        minResRX2FFTBTFSEL_cnt_next = minResRX2FFTBTFSEL_cnt + 8'b00000001;
      end
    end
    minResRX2FFTBTFSEL_btfInReg_vld_next = minResRX2FFTBTFSEL_dMemOutReg_vld;
    minResRX2FFTBTFSEL_dMemOutReg_vld_next = dMemOut_vld;
    minResRX2FFTBTFSEL_dMemOut1Reg_re_next = dMemOut1_re;
    minResRX2FFTBTFSEL_dMemOut1Reg_im_next = dMemOut1_im;
    minResRX2FFTBTFSEL_dMemOut2Reg_re_next = dMemOut2_re;
    minResRX2FFTBTFSEL_dMemOut2Reg_im_next = dMemOut2_im;
    btfIn1_re_1 = minResRX2FFTBTFSEL_btfIn1Reg_re;
    btfIn1_im_1 = minResRX2FFTBTFSEL_btfIn1Reg_im;
    btfIn2_re_1 = minResRX2FFTBTFSEL_btfIn2Reg_re;
    btfIn2_im_1 = minResRX2FFTBTFSEL_btfIn2Reg_im;
    btfIn_vld_1 = minResRX2FFTBTFSEL_btfInReg_vld;
  end



  assign btfIn1_re = btfIn1_re_1;

  assign btfIn1_im = btfIn1_im_1;

  assign btfIn2_re = btfIn2_re_1;

  assign btfIn2_im = btfIn2_im_1;

  assign btfIn_vld = btfIn_vld_1;

endmodule  // MINRESRX2FFT_BTFSEL

