// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\FFTHDLOptimizedExample_Streaming\Complex4Multiply_block19.v
// Created: 2024-05-11 19:34:42
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Complex4Multiply_block19
// Source Path: FFTHDLOptimizedExample_Streaming/FFT Streaming/FFT/TWDLMULT_SDNF1_7/Complex4Multiply
// Hierarchy Level: 3
// Model version: 8.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Complex4Multiply_block19
          (clk,
           reset,
           din2_re_dly3,
           din2_im_dly3,
           di2_vld_dly3,
           twdl_7_6_re,
           twdl_7_6_im,
           twdlXdin_6_re,
           twdlXdin_6_im);


  input   clk;
  input   reset;
  input   signed [22:0] din2_re_dly3;  // sfix23_En13
  input   signed [22:0] din2_im_dly3;  // sfix23_En13
  input   di2_vld_dly3;
  input   signed [15:0] twdl_7_6_re;  // sfix16_En14
  input   signed [15:0] twdl_7_6_im;  // sfix16_En14
  output  signed [22:0] twdlXdin_6_re;  // sfix23_En13
  output  signed [22:0] twdlXdin_6_im;  // sfix23_En13


  reg signed [22:0] din_re_reg;  // sfix23_En13
  reg signed [22:0] din_im_reg;  // sfix23_En13
  reg signed [15:0] twdl_re_reg;  // sfix16_En14
  reg signed [15:0] twdl_im_reg;  // sfix16_En14
  reg signed [22:0] Complex4Multiply_din1_re_pipe1;  // sfix23
  reg signed [22:0] Complex4Multiply_din1_im_pipe1;  // sfix23
  reg signed [38:0] Complex4Multiply_mult1_re_pipe1;  // sfix39
  reg signed [38:0] Complex4Multiply_mult2_re_pipe1;  // sfix39
  reg signed [38:0] Complex4Multiply_mult1_im_pipe1;  // sfix39
  reg signed [38:0] Complex4Multiply_mult2_im_pipe1;  // sfix39
  reg signed [15:0] Complex4Multiply_twiddle_re_pipe1;  // sfix16
  reg signed [15:0] Complex4Multiply_twiddle_im_pipe1;  // sfix16
  reg signed [38:0] prod1_re;  // sfix39_En27
  reg signed [38:0] prod1_im;  // sfix39_En27
  reg signed [38:0] prod2_re;  // sfix39_En27
  reg signed [38:0] prod2_im;  // sfix39_En27
  reg  din_vld_dly1;
  reg  din_vld_dly2;
  reg  din_vld_dly3;
  reg  prod_vld;
  reg signed [39:0] Complex4Add_multRes_re_reg;  // sfix40
  reg signed [39:0] Complex4Add_multRes_im_reg;  // sfix40
  reg  Complex4Add_prod_vld_reg1;
  reg signed [38:0] Complex4Add_prod1_re_reg;  // sfix39
  reg signed [38:0] Complex4Add_prod1_im_reg;  // sfix39
  reg signed [38:0] Complex4Add_prod2_re_reg;  // sfix39
  reg signed [38:0] Complex4Add_prod2_im_reg;  // sfix39
  wire signed [39:0] Complex4Add_multRes_re_reg_next;  // sfix40_En27
  wire signed [39:0] Complex4Add_multRes_im_reg_next;  // sfix40_En27
  wire signed [39:0] Complex4Add_sub_cast;  // sfix40_En27
  wire signed [39:0] Complex4Add_sub_cast_1;  // sfix40_En27
  wire signed [39:0] Complex4Add_add_cast;  // sfix40_En27
  wire signed [39:0] Complex4Add_add_cast_1;  // sfix40_En27
  wire signed [39:0] mulResFP_re;  // sfix40_En27
  wire signed [39:0] mulResFP_im;  // sfix40_En27
  reg  twdlXdin2_vld;


  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        din_re_reg <= 23'sb00000000000000000000000;
      end
      else begin
        din_re_reg <= din2_re_dly3;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        din_im_reg <= 23'sb00000000000000000000000;
      end
      else begin
        din_im_reg <= din2_im_dly3;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        twdl_re_reg <= 16'sb0000000000000000;
      end
      else begin
        twdl_re_reg <= twdl_7_6_re;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        twdl_im_reg <= 16'sb0000000000000000;
      end
      else begin
        twdl_im_reg <= twdl_7_6_im;
      end
    end



  // Complex4Multiply
  always @(posedge clk)
    begin : Complex4Multiply_process
      prod1_re <= Complex4Multiply_mult1_re_pipe1;
      prod2_re <= Complex4Multiply_mult2_re_pipe1;
      prod1_im <= Complex4Multiply_mult1_im_pipe1;
      prod2_im <= Complex4Multiply_mult2_im_pipe1;
      Complex4Multiply_mult1_re_pipe1 <= Complex4Multiply_din1_re_pipe1 * Complex4Multiply_twiddle_re_pipe1;
      Complex4Multiply_mult2_re_pipe1 <= Complex4Multiply_din1_im_pipe1 * Complex4Multiply_twiddle_im_pipe1;
      Complex4Multiply_mult1_im_pipe1 <= Complex4Multiply_din1_re_pipe1 * Complex4Multiply_twiddle_im_pipe1;
      Complex4Multiply_mult2_im_pipe1 <= Complex4Multiply_din1_im_pipe1 * Complex4Multiply_twiddle_re_pipe1;
      Complex4Multiply_twiddle_re_pipe1 <= twdl_re_reg;
      Complex4Multiply_twiddle_im_pipe1 <= twdl_im_reg;
      Complex4Multiply_din1_re_pipe1 <= din_re_reg;
      Complex4Multiply_din1_im_pipe1 <= din_im_reg;
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        din_vld_dly1 <= 1'b0;
      end
      else begin
        din_vld_dly1 <= di2_vld_dly3;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        din_vld_dly2 <= 1'b0;
      end
      else begin
        din_vld_dly2 <= din_vld_dly1;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        din_vld_dly3 <= 1'b0;
      end
      else begin
        din_vld_dly3 <= din_vld_dly2;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        prod_vld <= 1'b0;
      end
      else begin
        prod_vld <= din_vld_dly3;
      end
    end



  // Complex4Add
  always @(posedge clk or posedge reset)
    begin : Complex4Add_process
      if (reset == 1'b1) begin
        Complex4Add_multRes_re_reg <= 40'sh0000000000;
        Complex4Add_multRes_im_reg <= 40'sh0000000000;
        Complex4Add_prod1_re_reg <= 39'sh0000000000;
        Complex4Add_prod1_im_reg <= 39'sh0000000000;
        Complex4Add_prod2_re_reg <= 39'sh0000000000;
        Complex4Add_prod2_im_reg <= 39'sh0000000000;
        Complex4Add_prod_vld_reg1 <= 1'b0;
        twdlXdin2_vld <= 1'b0;
      end
      else begin
        Complex4Add_multRes_re_reg <= Complex4Add_multRes_re_reg_next;
        Complex4Add_multRes_im_reg <= Complex4Add_multRes_im_reg_next;
        Complex4Add_prod1_re_reg <= prod1_re;
        Complex4Add_prod1_im_reg <= prod1_im;
        Complex4Add_prod2_re_reg <= prod2_re;
        Complex4Add_prod2_im_reg <= prod2_im;
        twdlXdin2_vld <= Complex4Add_prod_vld_reg1;
        Complex4Add_prod_vld_reg1 <= prod_vld;
      end
    end

  assign Complex4Add_sub_cast = {Complex4Add_prod1_re_reg[38], Complex4Add_prod1_re_reg};
  assign Complex4Add_sub_cast_1 = {Complex4Add_prod2_re_reg[38], Complex4Add_prod2_re_reg};
  assign Complex4Add_multRes_re_reg_next = Complex4Add_sub_cast - Complex4Add_sub_cast_1;
  assign Complex4Add_add_cast = {Complex4Add_prod1_im_reg[38], Complex4Add_prod1_im_reg};
  assign Complex4Add_add_cast_1 = {Complex4Add_prod2_im_reg[38], Complex4Add_prod2_im_reg};
  assign Complex4Add_multRes_im_reg_next = Complex4Add_add_cast + Complex4Add_add_cast_1;
  assign mulResFP_re = Complex4Add_multRes_re_reg;
  assign mulResFP_im = Complex4Add_multRes_im_reg;



  assign twdlXdin_6_re = mulResFP_re[36:14];



  assign twdlXdin_6_im = mulResFP_im[36:14];



endmodule  // Complex4Multiply_block19

