// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\FFTHDLOptimizedExample_Streaming\Complex4Multiply_block5.v
// Created: 2024-05-11 19:34:42
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Complex4Multiply_block5
// Source Path: FFTHDLOptimizedExample_Streaming/FFT Streaming/FFT/RADIX22FFT_SDF1_3/Complex4Multiply
// Hierarchy Level: 3
// Model version: 8.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Complex4Multiply_block5
          (clk,
           reset,
           din_re,
           din_im,
           din_3_vld_dly,
           twdl_3_7_re,
           twdl_3_7_im,
           dinXTwdl_re,
           dinXTwdl_im,
           dinXTwdl_3_7_vld);


  input   clk;
  input   reset;
  input   signed [18:0] din_re;  // sfix19_En13
  input   signed [18:0] din_im;  // sfix19_En13
  input   din_3_vld_dly;
  input   signed [15:0] twdl_3_7_re;  // sfix16_En14
  input   signed [15:0] twdl_3_7_im;  // sfix16_En14
  output  signed [18:0] dinXTwdl_re;  // sfix19_En13
  output  signed [18:0] dinXTwdl_im;  // sfix19_En13
  output  dinXTwdl_3_7_vld;


  reg signed [18:0] din_re_reg;  // sfix19_En13
  reg signed [18:0] din_im_reg;  // sfix19_En13
  reg signed [15:0] twdl_re_reg;  // sfix16_En14
  reg signed [15:0] twdl_im_reg;  // sfix16_En14
  reg signed [18:0] Complex4Multiply_din1_re_pipe1;  // sfix19
  reg signed [18:0] Complex4Multiply_din1_im_pipe1;  // sfix19
  reg signed [34:0] Complex4Multiply_mult1_re_pipe1;  // sfix35
  reg signed [34:0] Complex4Multiply_mult2_re_pipe1;  // sfix35
  reg signed [34:0] Complex4Multiply_mult1_im_pipe1;  // sfix35
  reg signed [34:0] Complex4Multiply_mult2_im_pipe1;  // sfix35
  reg signed [15:0] Complex4Multiply_twiddle_re_pipe1;  // sfix16
  reg signed [15:0] Complex4Multiply_twiddle_im_pipe1;  // sfix16
  reg signed [34:0] prod1_re;  // sfix35_En27
  reg signed [34:0] prod1_im;  // sfix35_En27
  reg signed [34:0] prod2_re;  // sfix35_En27
  reg signed [34:0] prod2_im;  // sfix35_En27
  reg  din_vld_dly1;
  reg  din_vld_dly2;
  reg  din_vld_dly3;
  reg  prod_vld;
  reg signed [35:0] Complex4Add_multRes_re_reg;  // sfix36
  reg signed [35:0] Complex4Add_multRes_im_reg;  // sfix36
  reg  Complex4Add_prod_vld_reg1;
  reg signed [34:0] Complex4Add_prod1_re_reg;  // sfix35
  reg signed [34:0] Complex4Add_prod1_im_reg;  // sfix35
  reg signed [34:0] Complex4Add_prod2_re_reg;  // sfix35
  reg signed [34:0] Complex4Add_prod2_im_reg;  // sfix35
  wire signed [35:0] Complex4Add_multRes_re_reg_next;  // sfix36_En27
  wire signed [35:0] Complex4Add_multRes_im_reg_next;  // sfix36_En27
  wire signed [35:0] Complex4Add_sub_cast;  // sfix36_En27
  wire signed [35:0] Complex4Add_sub_cast_1;  // sfix36_En27
  wire signed [35:0] Complex4Add_add_cast;  // sfix36_En27
  wire signed [35:0] Complex4Add_add_cast_1;  // sfix36_En27
  wire signed [35:0] mulResFP_re;  // sfix36_En27
  wire signed [35:0] mulResFP_im;  // sfix36_En27
  reg  dinXTwdl_3_7_vld_1;


  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        din_re_reg <= 19'sb0000000000000000000;
      end
      else begin
        din_re_reg <= din_re;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        din_im_reg <= 19'sb0000000000000000000;
      end
      else begin
        din_im_reg <= din_im;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        twdl_re_reg <= 16'sb0000000000000000;
      end
      else begin
        twdl_re_reg <= twdl_3_7_re;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        twdl_im_reg <= 16'sb0000000000000000;
      end
      else begin
        twdl_im_reg <= twdl_3_7_im;
      end
    end



  // Complex4Multiply
  always @(posedge clk)
    begin : Complex4Multiply_process
      prod1_re <= Complex4Multiply_mult1_re_pipe1;
      prod2_re <= Complex4Multiply_mult2_re_pipe1;
      prod1_im <= Complex4Multiply_mult1_im_pipe1;
      prod2_im <= Complex4Multiply_mult2_im_pipe1;
      Complex4Multiply_mult1_re_pipe1 <= Complex4Multiply_din1_re_pipe1 * Complex4Multiply_twiddle_re_pipe1;
      Complex4Multiply_mult2_re_pipe1 <= Complex4Multiply_din1_im_pipe1 * Complex4Multiply_twiddle_im_pipe1;
      Complex4Multiply_mult1_im_pipe1 <= Complex4Multiply_din1_re_pipe1 * Complex4Multiply_twiddle_im_pipe1;
      Complex4Multiply_mult2_im_pipe1 <= Complex4Multiply_din1_im_pipe1 * Complex4Multiply_twiddle_re_pipe1;
      Complex4Multiply_twiddle_re_pipe1 <= twdl_re_reg;
      Complex4Multiply_twiddle_im_pipe1 <= twdl_im_reg;
      Complex4Multiply_din1_re_pipe1 <= din_re_reg;
      Complex4Multiply_din1_im_pipe1 <= din_im_reg;
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        din_vld_dly1 <= 1'b0;
      end
      else begin
        din_vld_dly1 <= din_3_vld_dly;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        din_vld_dly2 <= 1'b0;
      end
      else begin
        din_vld_dly2 <= din_vld_dly1;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        din_vld_dly3 <= 1'b0;
      end
      else begin
        din_vld_dly3 <= din_vld_dly2;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        prod_vld <= 1'b0;
      end
      else begin
        prod_vld <= din_vld_dly3;
      end
    end



  // Complex4Add
  always @(posedge clk or posedge reset)
    begin : Complex4Add_process
      if (reset == 1'b1) begin
        Complex4Add_multRes_re_reg <= 36'sh000000000;
        Complex4Add_multRes_im_reg <= 36'sh000000000;
        Complex4Add_prod1_re_reg <= 35'sh000000000;
        Complex4Add_prod1_im_reg <= 35'sh000000000;
        Complex4Add_prod2_re_reg <= 35'sh000000000;
        Complex4Add_prod2_im_reg <= 35'sh000000000;
        Complex4Add_prod_vld_reg1 <= 1'b0;
        dinXTwdl_3_7_vld_1 <= 1'b0;
      end
      else begin
        Complex4Add_multRes_re_reg <= Complex4Add_multRes_re_reg_next;
        Complex4Add_multRes_im_reg <= Complex4Add_multRes_im_reg_next;
        Complex4Add_prod1_re_reg <= prod1_re;
        Complex4Add_prod1_im_reg <= prod1_im;
        Complex4Add_prod2_re_reg <= prod2_re;
        Complex4Add_prod2_im_reg <= prod2_im;
        dinXTwdl_3_7_vld_1 <= Complex4Add_prod_vld_reg1;
        Complex4Add_prod_vld_reg1 <= prod_vld;
      end
    end

  assign Complex4Add_sub_cast = {Complex4Add_prod1_re_reg[34], Complex4Add_prod1_re_reg};
  assign Complex4Add_sub_cast_1 = {Complex4Add_prod2_re_reg[34], Complex4Add_prod2_re_reg};
  assign Complex4Add_multRes_re_reg_next = Complex4Add_sub_cast - Complex4Add_sub_cast_1;
  assign Complex4Add_add_cast = {Complex4Add_prod1_im_reg[34], Complex4Add_prod1_im_reg};
  assign Complex4Add_add_cast_1 = {Complex4Add_prod2_im_reg[34], Complex4Add_prod2_im_reg};
  assign Complex4Add_multRes_im_reg_next = Complex4Add_add_cast + Complex4Add_add_cast_1;
  assign mulResFP_re = Complex4Add_multRes_re_reg;
  assign mulResFP_im = Complex4Add_multRes_im_reg;



  assign dinXTwdl_re = mulResFP_re[32:14];



  assign dinXTwdl_im = mulResFP_im[32:14];



  assign dinXTwdl_3_7_vld = dinXTwdl_3_7_vld_1;

endmodule  // Complex4Multiply_block5

