// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\FFTHDLOptimizedExample_Streaming\RADIX22FFT_SDNF1_7.v
// Created: 2024-05-11 19:34:42
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDNF1_7
// Source Path: FFTHDLOptimizedExample_Streaming/FFT Streaming/FFT/RADIX22FFT_SDNF1_7
// Hierarchy Level: 2
// Model version: 8.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDNF1_7
          (clk,
           reset,
           twdlXdin_1_re,
           twdlXdin_1_im,
           twdlXdin_5_re,
           twdlXdin_5_im,
           twdlXdin_1_vld,
           dout_1_re,
           dout_1_im,
           dout_2_re,
           dout_2_im,
           dout_1_vld);


  input   clk;
  input   reset;
  input   signed [22:0] twdlXdin_1_re;  // sfix23_En13
  input   signed [22:0] twdlXdin_1_im;  // sfix23_En13
  input   signed [22:0] twdlXdin_5_re;  // sfix23_En13
  input   signed [22:0] twdlXdin_5_im;  // sfix23_En13
  input   twdlXdin_1_vld;
  output  signed [22:0] dout_1_re;  // sfix23_En13
  output  signed [22:0] dout_1_im;  // sfix23_En13
  output  signed [22:0] dout_2_re;  // sfix23_En13
  output  signed [22:0] dout_2_im;  // sfix23_En13
  output  dout_1_vld;


  reg signed [23:0] Radix22ButterflyG1_NF_btf1_re_reg;  // sfix24
  reg signed [23:0] Radix22ButterflyG1_NF_btf1_im_reg;  // sfix24
  reg signed [23:0] Radix22ButterflyG1_NF_btf2_re_reg;  // sfix24
  reg signed [23:0] Radix22ButterflyG1_NF_btf2_im_reg;  // sfix24
  reg  Radix22ButterflyG1_NF_dinXtwdl_vld_dly1;
  reg signed [23:0] Radix22ButterflyG1_NF_btf1_re_reg_next;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG1_NF_btf1_im_reg_next;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG1_NF_btf2_re_reg_next;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG1_NF_btf2_im_reg_next;  // sfix24_En13
  reg  Radix22ButterflyG1_NF_dinXtwdl_vld_dly1_next;
  reg signed [22:0] dout_1_re_1;  // sfix23_En13
  reg signed [22:0] dout_1_im_1;  // sfix23_En13
  reg signed [22:0] dout_2_re_1;  // sfix23_En13
  reg signed [22:0] dout_2_im_1;  // sfix23_En13
  reg  dout_1_vld_1;
  reg signed [23:0] Radix22ButterflyG1_NF_add_cast;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG1_NF_add_cast_0;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG1_NF_sub_cast;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG1_NF_sub_cast_0;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG1_NF_add_cast_1;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG1_NF_add_cast_2;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG1_NF_sub_cast_1;  // sfix24_En13
  reg signed [23:0] Radix22ButterflyG1_NF_sub_cast_2;  // sfix24_En13


  // Radix22ButterflyG1_NF
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG1_NF_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_NF_btf1_re_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG1_NF_btf1_im_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG1_NF_btf2_re_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG1_NF_btf2_im_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG1_NF_dinXtwdl_vld_dly1 <= 1'b0;
      end
      else begin
        Radix22ButterflyG1_NF_btf1_re_reg <= Radix22ButterflyG1_NF_btf1_re_reg_next;
        Radix22ButterflyG1_NF_btf1_im_reg <= Radix22ButterflyG1_NF_btf1_im_reg_next;
        Radix22ButterflyG1_NF_btf2_re_reg <= Radix22ButterflyG1_NF_btf2_re_reg_next;
        Radix22ButterflyG1_NF_btf2_im_reg <= Radix22ButterflyG1_NF_btf2_im_reg_next;
        Radix22ButterflyG1_NF_dinXtwdl_vld_dly1 <= Radix22ButterflyG1_NF_dinXtwdl_vld_dly1_next;
      end
    end

  always @(Radix22ButterflyG1_NF_btf1_im_reg, Radix22ButterflyG1_NF_btf1_re_reg,
       Radix22ButterflyG1_NF_btf2_im_reg, Radix22ButterflyG1_NF_btf2_re_reg,
       Radix22ButterflyG1_NF_dinXtwdl_vld_dly1, twdlXdin_1_im, twdlXdin_1_re,
       twdlXdin_1_vld, twdlXdin_5_im, twdlXdin_5_re) begin
    Radix22ButterflyG1_NF_add_cast = 24'sb000000000000000000000000;
    Radix22ButterflyG1_NF_add_cast_0 = 24'sb000000000000000000000000;
    Radix22ButterflyG1_NF_sub_cast = 24'sb000000000000000000000000;
    Radix22ButterflyG1_NF_sub_cast_0 = 24'sb000000000000000000000000;
    Radix22ButterflyG1_NF_add_cast_1 = 24'sb000000000000000000000000;
    Radix22ButterflyG1_NF_add_cast_2 = 24'sb000000000000000000000000;
    Radix22ButterflyG1_NF_sub_cast_1 = 24'sb000000000000000000000000;
    Radix22ButterflyG1_NF_sub_cast_2 = 24'sb000000000000000000000000;
    Radix22ButterflyG1_NF_btf1_re_reg_next = Radix22ButterflyG1_NF_btf1_re_reg;
    Radix22ButterflyG1_NF_btf1_im_reg_next = Radix22ButterflyG1_NF_btf1_im_reg;
    Radix22ButterflyG1_NF_btf2_re_reg_next = Radix22ButterflyG1_NF_btf2_re_reg;
    Radix22ButterflyG1_NF_btf2_im_reg_next = Radix22ButterflyG1_NF_btf2_im_reg;
    Radix22ButterflyG1_NF_dinXtwdl_vld_dly1_next = twdlXdin_1_vld;
    if (twdlXdin_1_vld) begin
      Radix22ButterflyG1_NF_add_cast = {twdlXdin_1_re[22], twdlXdin_1_re};
      Radix22ButterflyG1_NF_add_cast_0 = {twdlXdin_5_re[22], twdlXdin_5_re};
      Radix22ButterflyG1_NF_btf1_re_reg_next = Radix22ButterflyG1_NF_add_cast + Radix22ButterflyG1_NF_add_cast_0;
      Radix22ButterflyG1_NF_sub_cast = {twdlXdin_1_re[22], twdlXdin_1_re};
      Radix22ButterflyG1_NF_sub_cast_0 = {twdlXdin_5_re[22], twdlXdin_5_re};
      Radix22ButterflyG1_NF_btf2_re_reg_next = Radix22ButterflyG1_NF_sub_cast - Radix22ButterflyG1_NF_sub_cast_0;
      Radix22ButterflyG1_NF_add_cast_1 = {twdlXdin_1_im[22], twdlXdin_1_im};
      Radix22ButterflyG1_NF_add_cast_2 = {twdlXdin_5_im[22], twdlXdin_5_im};
      Radix22ButterflyG1_NF_btf1_im_reg_next = Radix22ButterflyG1_NF_add_cast_1 + Radix22ButterflyG1_NF_add_cast_2;
      Radix22ButterflyG1_NF_sub_cast_1 = {twdlXdin_1_im[22], twdlXdin_1_im};
      Radix22ButterflyG1_NF_sub_cast_2 = {twdlXdin_5_im[22], twdlXdin_5_im};
      Radix22ButterflyG1_NF_btf2_im_reg_next = Radix22ButterflyG1_NF_sub_cast_1 - Radix22ButterflyG1_NF_sub_cast_2;
    end
    dout_1_re_1 = Radix22ButterflyG1_NF_btf1_re_reg[22:0];
    dout_1_im_1 = Radix22ButterflyG1_NF_btf1_im_reg[22:0];
    dout_2_re_1 = Radix22ButterflyG1_NF_btf2_re_reg[22:0];
    dout_2_im_1 = Radix22ButterflyG1_NF_btf2_im_reg[22:0];
    dout_1_vld_1 = Radix22ButterflyG1_NF_dinXtwdl_vld_dly1;
  end



  assign dout_1_re = dout_1_re_1;

  assign dout_1_im = dout_1_im_1;

  assign dout_2_re = dout_2_re_1;

  assign dout_2_im = dout_2_im_1;

  assign dout_1_vld = dout_1_vld_1;

endmodule  // RADIX22FFT_SDNF1_7

