// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\FFTHDLOptimizedExample_Streaming\RADIX22FFT_SDF2_6_block2.v
// Created: 2024-05-11 19:34:42
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF2_6_block2
// Source Path: FFTHDLOptimizedExample_Streaming/FFT Streaming/FFT/RADIX22FFT_SDF2_6
// Hierarchy Level: 2
// Model version: 8.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF2_6_block2
          (clk,
           reset,
           dout_5_4_re,
           dout_5_4_im,
           dout_5_1_vld,
           rd_6_Addr,
           rd_6_Enb,
           proc_6_enb,
           multiply_6_J,
           dout_6_4_re,
           dout_6_4_im);


  input   clk;
  input   reset;
  input   signed [20:0] dout_5_4_re;  // sfix21_En13
  input   signed [20:0] dout_5_4_im;  // sfix21_En13
  input   dout_5_1_vld;
  input   rd_6_Addr;
  input   rd_6_Enb;
  input   proc_6_enb;
  input   multiply_6_J;
  output  signed [21:0] dout_6_4_re;  // sfix22_En13
  output  signed [21:0] dout_6_4_im;  // sfix22_En13


  wire signed [21:0] din_re;  // sfix22_En13
  wire signed [21:0] din_im;  // sfix22_En13
  wire saveEnb;
  wire dinVld;
  reg signed [21:0] din_re_dly1;  // sfix22_En13
  reg signed [21:0] btfin_re;  // sfix22_En13
  reg signed [21:0] din_im_dly1;  // sfix22_En13
  reg signed [21:0] btfin_im;  // sfix22_En13
  wire mulIn_vld;
  reg  procEnb_dly1;
  reg  btfin_vld;
  reg  x_vld;
  reg  x_vld_dly;
  reg signed [21:0] x_im;  // sfix22_En13
  reg signed [21:0] x_im_dly;  // sfix22_En13
  wire signed [21:0] wrData_re;  // sfix22_En13
  wire signed [21:0] wrData_im;  // sfix22_En13
  wire wrAddr;  // ufix1
  wire wrEnb;
  reg signed [21:0] twoLocationReg_0_MEM_re_0;  // sfix22
  reg signed [21:0] twoLocationReg_0_MEM_im_0;  // sfix22
  reg signed [21:0] twoLocationReg_0_MEM_re_1;  // sfix22
  reg signed [21:0] twoLocationReg_0_MEM_im_1;  // sfix22
  reg signed [21:0] twoLocationReg_0_dout_re_reg;  // sfix22
  reg signed [21:0] twoLocationReg_0_dout_im_reg;  // sfix22
  reg signed [21:0] twoLocationReg_0_MEM_re_0_next;  // sfix22_En13
  reg signed [21:0] twoLocationReg_0_MEM_im_0_next;  // sfix22_En13
  reg signed [21:0] twoLocationReg_0_MEM_re_1_next;  // sfix22_En13
  reg signed [21:0] twoLocationReg_0_MEM_im_1_next;  // sfix22_En13
  reg signed [21:0] twoLocationReg_0_dout_re_reg_next;  // sfix22_En13
  reg signed [21:0] twoLocationReg_0_dout_im_reg_next;  // sfix22_En13
  reg signed [21:0] x_re;  // sfix22_En13
  reg signed [21:0] x_re_dly;  // sfix22_En13
  reg  Radix22ButterflyG2_procEnb_dly;
  reg  Radix22ButterflyG2_procEnb_dly1;
  reg  Radix22ButterflyG2_procEnb_dly2;
  reg signed [22:0] Radix22ButterflyG2_btf1_re_reg;  // sfix23
  reg signed [22:0] Radix22ButterflyG2_btf1_im_reg;  // sfix23
  reg signed [22:0] Radix22ButterflyG2_btf2_re_reg;  // sfix23
  reg signed [22:0] Radix22ButterflyG2_btf2_im_reg;  // sfix23
  reg signed [21:0] Radix22ButterflyG2_din_re_dly;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_din_im_dly;  // sfix22
  reg  Radix22ButterflyG2_din_vld_dly;
  reg signed [21:0] Radix22ButterflyG2_x_re_dly;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_x_im_dly;  // sfix22
  reg  Radix22ButterflyG2_x_vld_dly;
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  // sfix22
  reg  Radix22ButterflyG2_multiply_J_dly1;
  reg  Radix22ButterflyG2_procEnb_dly_next;
  reg  Radix22ButterflyG2_procEnb_dly1_next;
  reg  Radix22ButterflyG2_procEnb_dly2_next;
  reg signed [22:0] Radix22ButterflyG2_btf1_re_reg_next;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_btf1_im_reg_next;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_btf2_re_reg_next;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_btf2_im_reg_next;  // sfix23_En13
  reg signed [21:0] Radix22ButterflyG2_din_re_dly_next;  // sfix22_En13
  reg signed [21:0] Radix22ButterflyG2_din_im_dly_next;  // sfix22_En13
  reg  Radix22ButterflyG2_din_vld_dly_next;
  reg signed [21:0] Radix22ButterflyG2_x_re_dly_next;  // sfix22_En13
  reg signed [21:0] Radix22ButterflyG2_x_im_dly_next;  // sfix22_En13
  reg  Radix22ButterflyG2_x_vld_dly_next;
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_re_dly1_next;  // sfix22_En13
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_im_dly1_next;  // sfix22_En13
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_re_dly2_next;  // sfix22_En13
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_im_dly2_next;  // sfix22_En13
  reg  Radix22ButterflyG2_multiply_J_dly1_next;
  reg signed [21:0] xf_re;  // sfix22_En13
  reg signed [21:0] xf_im;  // sfix22_En13
  reg  xf_vld;
  reg signed [21:0] dinf_re;  // sfix22_En13
  reg signed [21:0] dinf_im;  // sfix22_En13
  reg  dinf_vld;
  reg signed [21:0] btf1_re;  // sfix22_En13
  reg signed [21:0] btf1_im;  // sfix22_En13
  reg signed [21:0] btf2_re;  // sfix22_En13
  reg signed [21:0] btf2_im;  // sfix22_En13
  reg  btfout_vld;
  reg signed [22:0] Radix22ButterflyG2_add_cast;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_add_cast_0;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_add_cast_1;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_add_cast_2;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_sub_cast;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_sub_cast_0;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_sub_cast_1;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_sub_cast_2;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_add_cast_3;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_add_cast_4;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_add_cast_5;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_add_cast_6;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_sub_cast_3;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_sub_cast_4;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_sub_cast_5;  // sfix23_En13
  reg signed [22:0] Radix22ButterflyG2_sub_cast_6;  // sfix23_En13


  assign din_re = {dout_5_4_re[20], dout_5_4_re};



  assign din_im = {dout_5_4_im[20], dout_5_4_im};



  assign saveEnb =  ~ proc_6_enb;



  assign dinVld = dout_5_1_vld & saveEnb;



  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        din_re_dly1 <= 22'sb0000000000000000000000;
      end
      else begin
        din_re_dly1 <= din_re;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        btfin_re <= 22'sb0000000000000000000000;
      end
      else begin
        btfin_re <= din_re_dly1;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        din_im_dly1 <= 22'sb0000000000000000000000;
      end
      else begin
        din_im_dly1 <= din_im;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        btfin_im <= 22'sb0000000000000000000000;
      end
      else begin
        btfin_im <= din_im_dly1;
      end
    end



  assign mulIn_vld = dout_5_1_vld & proc_6_enb;



  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        procEnb_dly1 <= 1'b0;
      end
      else begin
        procEnb_dly1 <= mulIn_vld;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        btfin_vld <= 1'b0;
      end
      else begin
        btfin_vld <= procEnb_dly1;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        x_vld <= rd_6_Enb;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        x_vld_dly <= x_vld;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_8_process
      if (reset == 1'b1) begin
        x_im_dly <= 22'sb0000000000000000000000;
      end
      else begin
        x_im_dly <= x_im;
      end
    end



  // twoLocationReg_0
  always @(posedge clk or posedge reset)
    begin : twoLocationReg_0_process
      if (reset == 1'b1) begin
        twoLocationReg_0_MEM_re_0 <= 22'sb0000000000000000000000;
        twoLocationReg_0_MEM_im_0 <= 22'sb0000000000000000000000;
        twoLocationReg_0_MEM_re_1 <= 22'sb0000000000000000000000;
        twoLocationReg_0_MEM_im_1 <= 22'sb0000000000000000000000;
        twoLocationReg_0_dout_re_reg <= 22'sb0000000000000000000000;
        twoLocationReg_0_dout_im_reg <= 22'sb0000000000000000000000;
      end
      else begin
        twoLocationReg_0_MEM_re_0 <= twoLocationReg_0_MEM_re_0_next;
        twoLocationReg_0_MEM_im_0 <= twoLocationReg_0_MEM_im_0_next;
        twoLocationReg_0_MEM_re_1 <= twoLocationReg_0_MEM_re_1_next;
        twoLocationReg_0_MEM_im_1 <= twoLocationReg_0_MEM_im_1_next;
        twoLocationReg_0_dout_re_reg <= twoLocationReg_0_dout_re_reg_next;
        twoLocationReg_0_dout_im_reg <= twoLocationReg_0_dout_im_reg_next;
      end
    end

  always @(rd_6_Addr, twoLocationReg_0_MEM_im_0, twoLocationReg_0_MEM_im_1,
       twoLocationReg_0_MEM_re_0, twoLocationReg_0_MEM_re_1,
       twoLocationReg_0_dout_im_reg, twoLocationReg_0_dout_re_reg, wrAddr,
       wrData_im, wrData_re, wrEnb) begin
    twoLocationReg_0_MEM_re_0_next = twoLocationReg_0_MEM_re_0;
    twoLocationReg_0_MEM_im_0_next = twoLocationReg_0_MEM_im_0;
    twoLocationReg_0_MEM_re_1_next = twoLocationReg_0_MEM_re_1;
    twoLocationReg_0_MEM_im_1_next = twoLocationReg_0_MEM_im_1;
    if (rd_6_Addr) begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_1;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_1;
    end
    else begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_0;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_0;
    end
    if (wrEnb) begin
      if (wrAddr == 1'b1) begin
        twoLocationReg_0_MEM_re_1_next = wrData_re;
        twoLocationReg_0_MEM_im_1_next = wrData_im;
      end
      else begin
        twoLocationReg_0_MEM_re_0_next = wrData_re;
        twoLocationReg_0_MEM_im_0_next = wrData_im;
      end
    end
    x_re = twoLocationReg_0_dout_re_reg;
    x_im = twoLocationReg_0_dout_im_reg;
  end



  always @(posedge clk or posedge reset)
    begin : intdelay_9_process
      if (reset == 1'b1) begin
        x_re_dly <= 22'sb0000000000000000000000;
      end
      else begin
        x_re_dly <= x_re;
      end
    end



  // Radix22ButterflyG2
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG2_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_btf1_im_reg <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_btf2_re_reg <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_btf2_im_reg <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_din_re_dly <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_din_im_dly <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_x_im_dly <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
        Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
        Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
        Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
        Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
        Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
        Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
        Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
        Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
        Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
        Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
        Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
        Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_next;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_next;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_next;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_next;
        Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_next;
      end
    end

  always @(Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_im_dly2,
       Radix22ButterflyG2_dinXTwdl_re_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_vld_dly, Radix22ButterflyG2_multiply_J_dly1,
       Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_vld_dly, btfin_im,
       btfin_re, btfin_vld, dinVld, din_im, din_re, multiply_6_J, x_im_dly,
       x_re_dly, x_vld_dly) begin
    Radix22ButterflyG2_add_cast_1 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast_2 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_1 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_2 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast_5 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast_6 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_5 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_6 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast_0 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_0 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast_3 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast_4 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_3 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_4 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = din_re;
    Radix22ButterflyG2_din_im_dly_next = din_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_add_cast_1 = {x_re_dly[21], x_re_dly};
      Radix22ButterflyG2_add_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[21], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast_1 + Radix22ButterflyG2_add_cast_2;
      Radix22ButterflyG2_sub_cast_1 = {x_re_dly[21], x_re_dly};
      Radix22ButterflyG2_sub_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[21], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast_1 - Radix22ButterflyG2_sub_cast_2;
      Radix22ButterflyG2_add_cast_5 = {x_im_dly[21], x_im_dly};
      Radix22ButterflyG2_add_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[21], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_add_cast_5 + Radix22ButterflyG2_add_cast_6;
      Radix22ButterflyG2_sub_cast_5 = {x_im_dly[21], x_im_dly};
      Radix22ButterflyG2_sub_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[21], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_sub_cast_5 - Radix22ButterflyG2_sub_cast_6;
    end
    else begin
      Radix22ButterflyG2_add_cast = {x_re_dly[21], x_re_dly};
      Radix22ButterflyG2_add_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[21], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast + Radix22ButterflyG2_add_cast_0;
      Radix22ButterflyG2_sub_cast = {x_re_dly[21], x_re_dly};
      Radix22ButterflyG2_sub_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[21], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast - Radix22ButterflyG2_sub_cast_0;
      Radix22ButterflyG2_add_cast_3 = {x_im_dly[21], x_im_dly};
      Radix22ButterflyG2_add_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[21], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_add_cast_3 + Radix22ButterflyG2_add_cast_4;
      Radix22ButterflyG2_sub_cast_3 = {x_im_dly[21], x_im_dly};
      Radix22ButterflyG2_sub_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[21], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_sub_cast_3 - Radix22ButterflyG2_sub_cast_4;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_next = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_next = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_next = btfin_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_next = btfin_im;
    Radix22ButterflyG2_multiply_J_dly1_next = multiply_6_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    btf1_re = Radix22ButterflyG2_btf1_re_reg[21:0];
    btf1_im = Radix22ButterflyG2_btf1_im_reg[21:0];
    btf2_re = Radix22ButterflyG2_btf2_re_reg[21:0];
    btf2_im = Radix22ButterflyG2_btf2_im_reg[21:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end



  SDFCommutator6_block2 u_SDFCOMMUTATOR_6 (.clk(clk),
                                           .reset(reset),
                                           .dout_5_1_vld(dout_5_1_vld),
                                           .xf_re(xf_re),  // sfix22_En13
                                           .xf_im(xf_im),  // sfix22_En13
                                           .xf_vld(xf_vld),
                                           .dinf_re(dinf_re),  // sfix22_En13
                                           .dinf_im(dinf_im),  // sfix22_En13
                                           .dinf_vld(dinf_vld),
                                           .btf1_re(btf1_re),  // sfix22_En13
                                           .btf1_im(btf1_im),  // sfix22_En13
                                           .btf2_re(btf2_re),  // sfix22_En13
                                           .btf2_im(btf2_im),  // sfix22_En13
                                           .btfout_vld(btfout_vld),
                                           .wrData_re(wrData_re),  // sfix22_En13
                                           .wrData_im(wrData_im),  // sfix22_En13
                                           .wrAddr(wrAddr),  // ufix1
                                           .wrEnb(wrEnb),
                                           .dout_6_4_re(dout_6_4_re),  // sfix22_En13
                                           .dout_6_4_im(dout_6_4_im)  // sfix22_En13
                                           );

endmodule  // RADIX22FFT_SDF2_6_block2

